options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud compute ssh praveenkumar_thati23a@backend --zone=us-central1-a --command="
          cd /home/praveenkumar_thati23a/taskmaster-backend &&
          git fetch origin dev &&
          git reset --hard origin/dev &&
          npm install &&
          pm2 restart taskmaster-backend || pm2 start server.js --name taskmaster-backend
        "
